service: cloudone-fss-gcp-slack-notifications

custom:
  defaultStage: prod
  stages:
    prod:
      SLACK_URL: <SLACK_URL>
      SLACK_CHANNEL: notifications
      SLACK_USERNAME: Cloud One File Storage Security
      DEPLOYMENT_REGION: <GCP_DEPLOYMENT_REGION>
      GCP_PROJECT_ID: <PROJECT_ID>
      EVENT_TYPE: providers/cloud.pubsub/eventTypes/topic.publish
      TRIGGER_RESOURCE: projects/<PROJECT_ID>/topics/<SCAN_RESULT_TOPIC_NAME>

provider:
  name: google
  stage: ${opt:stage, self:custom.defaultStage}
  runtime: python39
  region: ${self:custom.stages.${opt:stage, self:custom.defaultStage}.DEPLOYMENT_REGION}
  project: ${self:custom.stages.${opt:stage, self:custom.defaultStage}.GCP_PROJECT_ID}
  environment:
    SLACK_URL: ${self:custom.stages.${opt:stage, self:custom.defaultStage}.SLACK_URL}
    SLACK_CHANNEL: ${self:custom.stages.${opt:stage, self:custom.defaultStage}.SLACK_CHANNEL}
    SLACK_USERNAME: ${self:custom.stages.${opt:stage, self:custom.defaultStage}.SLACK_USERNAME}

frameworkVersion: '3'
plugins:
  - serverless-google-cloudfunctions

package:
  include:
    - "!node_modules/**"
    - "!docs/**"
    - "!.git/**"
  exclude:
    - README.md
    - .gitignore

functions:
  main:
    handler: main
    events:
      - event:
          eventType: ${self:custom.stages.${opt:stage, self:custom.defaultStage}.EVENT_TYPE}
          resource: ${self:custom.stages.${opt:stage, self:custom.defaultStage}.TRIGGER_RESOURCE}
