service: cloudone-fss-gcp-email-notifications
configValidationMode: error

custom:
  defaultStage: prod

params:
  prod:
    MAIL_FROM: <MAIL_FROM>
    MAIL_TO: <MAIL_TO>
    MAIL_SUBJECT: <MAIL_SUBJECT>
    MAIL_SERVER: <MAIL_SERVER>
    MAIL_LOCAL_HOST: <MAIL_LOCAL_HOST>
    MAIL_FORCE_TLS: <MAIL_FORCE_TLS>
    MAIL_DEBUG: <MAIL_DEBUG>
    DEPLOYMENT_REGION: <GCP_DEPLOYMENT_REGION>
    GCP_PROJECT_ID: <PROJECT_ID>
    EVENT_TYPE: providers/cloud.pubsub/eventTypes/topic.publish
    TRIGGER_RESOURCE: projects/<PROJECT_ID>/topics/<SCAN_RESULT_TOPIC_NAME>

provider:
  name: google
  stage: ${opt:stage, self:custom.defaultStage}
  runtime: python39
  region: ${param:DEPLOYMENT_REGION}
  project: ${param:GCP_PROJECT_ID}
  environment:
    MAIL_FROM: ${param:MAIL_FROM}
    MAIL_TO: ${param:MAIL_TO}
    MAIL_SUBJECT: ${param:MAIL_SUBJECT}
    MAIL_SERVER: ${param:MAIL_SERVER}
    MAIL_LOCAL_HOST: ${param:MAIL_LOCAL_HOST}
    MAIL_FORCE_TLS: ${param:MAIL_FORCE_TLS}
    MAIL_DEBUG: ${param:MAIL_DEBUG}

frameworkVersion: '3'
plugins:
  - serverless-google-cloudfunctions

package:
  patterns:
    - '!node_modules/**'
    - '!docs/**'
    - '!README.md'

functions:
  main:
    handler: main
    events:
      - event:
          eventType: ${param:EVENT_TYPE}
          resource: ${param:TRIGGER_RESOURCE}
